spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:15432/task-management-system
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
logging:
  config: classpath:logging/log4j2-prod.xml